name: Publish to Pub.dev

# 触发时机
on:
  push:
    tags:
      - 'v*'

# 流程需要执行的任务
jobs:
  # job名称
  publishing:
    # 跑在什么环境上
    runs-on: ubuntu-latest

    # 任务步骤
    steps:

      # 获取触发的tag
      # - name: Get version
      #   id: get_version
      #   run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      # 拉代码
      - name: "checkout"
        uses: actions/checkout@v2
        with:
          # tag_name: ${{ steps.get_version.outputs.VERSION }}
          tag_name: ${{ github.ref }}
      # 发布插件
      - name: ">>Dart package<<"
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.OAUTH_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.OAUTH_REFRESH_TOKEN }}
